### ISSUE TITLE
py2plantuml requires python version > 3.9

### ISSUE THREAD

**Issue by MSarfraz-CR** [2BlackCoffees/py2plantuml#2]
Due to `ast.dump` taking `indent` arguement, py2plantuml fails when running for version less 3.9 of python. The python version required along with a requirement.txt should be added to the repo

Stack trace:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "py2plantuml/__main__.py", line 37, in <module>
    main('/Users/jean-philippe.ulpiano/development/pygame/candy_cat', '/Users/jean-philippe.ulpiano/development/pygame/tmp-out')
  File "py2plantuml/__main__.py", line 29, in main
    ApplicationService.read_all_python_files(from_dir, out_dir, logger, PythonLanguage(logger), args.skip_uses_relation)
  File "py2plantuml/services/application_service.py", line 27, in read_all_python_files
    diagram_creation.get_data_structure(), file_name, from_dir)
  File "py2plantuml/infrastructure/python_adapter.py", line 32, in read_python_ast
    self.logger.log_trace(ast.dump(tree, indent=4))
TypeError: dump() got an unexpected keyword argument 'indent'
```

**Comment by 2BlackCoffees** [comment]
Thanks @MSarfraz-CR can you create it or would you prefer me to do so?

**Comment by 2BlackCoffees** [comment]
Hi @MSarfraz-CR I took care. BTW for the Python AST, maybe you can look at how I did it for CSharp: https://github.com/2BlackCoffees/py2plantuml/blob/main/docker/dotnet/ASTVisitor.cs. It is not finished yet but is kind of working.
